# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userLDAP', models.CharField(max_length=30)),
                ('privileges', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userLDAP', models.CharField(max_length=30)),
                ('changeId', models.CharField(max_length=15)),
                ('ch_team', models.CharField(max_length=50)),
                ('ch_desc', models.CharField(max_length=1500)),
                ('ch_date', models.CharField(max_length=20)),
                ('ch_category', models.CharField(max_length=50)),
                ('ch_ref', models.CharField(max_length=200)),
                ('ch_goal', models.CharField(max_length=200)),
                ('ch_server_account', models.CharField(max_length=200)),
                ('ch_owner1', models.CharField(max_length=200)),
                ('ch_owner2', models.CharField(max_length=200)),
                ('ch_stat_owner1', models.CharField(max_length=200)),
                ('ch_stat_owner2', models.CharField(max_length=200)),
                ('ch_stat_owner2_comment', models.CharField(max_length=200)),
                ('ch_stat_owner2_comment_date', models.CharField(max_length=200)),
                ('ch_final_status', models.CharField(max_length=200)),
                ('ch_final_status_date', models.CharField(max_length=200)),
                ('ch_file_pushed', models.CharField(max_length=200)),
                ('ch_rollback_file', models.CharField(max_length=200)),
                ('ch_ckId', models.CharField(max_length=200)),
                ('ch_template', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=15)),
                ('res', models.CharField(max_length=100)),
                ('res_req', models.CharField(max_length=200)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Change')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeTempOwner2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=15)),
                ('res', models.CharField(max_length=100)),
                ('res_req', models.CharField(max_length=200)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Change')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userLDAP', models.CharField(max_length=30)),
                ('checkId', models.CharField(max_length=15)),
                ('ck_team', models.CharField(max_length=50)),
                ('ck_category', models.CharField(max_length=200)),
                ('ck_date', models.CharField(max_length=200)),
                ('ck_hour', models.CharField(max_length=200)),
                ('ck_desc', models.CharField(max_length=200)),
                ('ck_ref_id', models.CharField(max_length=200)),
                ('ck_date_no_end', models.CharField(max_length=200)),
                ('ck_date_no_end_month', models.CharField(max_length=200)),
                ('ck_date_no_end_day', models.CharField(max_length=200)),
                ('ck_hour_no_end', models.CharField(max_length=200)),
                ('ck_serv_acc', models.CharField(max_length=200)),
                ('ck_changeId', models.CharField(max_length=200)),
                ('ck_title', models.CharField(max_length=200)),
                ('ck_priority', models.CharField(max_length=200)),
                ('ck_status', models.CharField(max_length=200)),
                ('ck_change_performed', models.CharField(max_length=200)),
                ('ck_done', models.CharField(max_length=200)),
                ('ck_action', models.CharField(max_length=200)),
                ('ck_rollback', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CheckComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=1500)),
                ('checkC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Check')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userLDAP', models.CharField(max_length=30)),
                ('problemId', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=15)),
                ('problemDesc', models.CharField(max_length=1500)),
                ('status', models.CharField(max_length=15)),
                ('problemOwner', models.CharField(max_length=50)),
                ('urgency', models.CharField(max_length=10)),
                ('importance', models.CharField(max_length=10)),
                ('priority', models.CharField(max_length=10)),
                ('jira', models.CharField(max_length=500)),
                ('lastAction', models.CharField(max_length=1500)),
                ('lastAction_time', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userLDAP', models.CharField(max_length=30)),
                ('projectId', models.CharField(max_length=15)),
                ('detectionDate', models.CharField(max_length=20)),
                ('pj_team', models.CharField(max_length=20)),
                ('pj_teamOp', models.CharField(max_length=20)),
                ('pj_projectDescription', models.CharField(max_length=2000)),
                ('pj_type', models.CharField(max_length=20)),
                ('pj_typeOfChange', models.CharField(max_length=20)),
                ('pj_accountable', models.CharField(max_length=200)),
                ('pj_area', models.CharField(max_length=20)),
                ('pj_impactScope', models.CharField(max_length=200)),
                ('pj_internalTarget', models.CharField(max_length=200)),
                ('pj_externalConstraint', models.CharField(max_length=200)),
                ('pj_externalConstraintType', models.CharField(max_length=100)),
                ('pj_status', models.CharField(max_length=20)),
                ('pj_requiredChanges', models.CharField(max_length=2000)),
                ('pj_jira', models.CharField(max_length=1000)),
                ('pj_rca', models.CharField(max_length=1000)),
                ('pj_descriptionNonMandatory', models.CharField(max_length=2000)),
                ('pj_impactDate', models.CharField(max_length=20)),
                ('pj_changeImplemDate', models.CharField(max_length=20)),
                ('pj_priority', models.CharField(max_length=20)),
                ('pj_cib', models.CharField(max_length=20)),
                ('pj_binaryAvail', models.CharField(max_length=20)),
                ('binaryAvailchose', models.CharField(max_length=20)),
                ('pj_goLiveDate', models.CharField(max_length=20)),
                ('pj_externalGoLiveDate', models.CharField(max_length=20)),
                ('pj_blockersHighBugs', models.CharField(max_length=200)),
                ('pj_nbClient', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeList', models.CharField(max_length=2000)),
                ('typeOfChangeList', models.CharField(max_length=2000)),
                ('areaList', models.CharField(max_length=2000)),
                ('externalConstraintTypeList', models.CharField(max_length=2000)),
                ('statusList', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='StatusAndCurrentTaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=3000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Project')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Problem'),
        ),
    ]
